### ISSUE TITLE
Nullpointer during Raycast in "Drop On Floor"

### ISSUE THREAD

**Issue by Mattiny** [Mattiny/yamms#9]
A user reported a Nullpointer Exception during the raycast in "Drop on Floor".

Analysis shows: Somehow the "get_world_3d().direct_space_state" must be null then.

**Comment by proti1** [comment]
I had the same problem, go to Project Settings (with Advanced Settings enabled) -> Physics -> 3D and uncheck "Run on Separate Thread".
After restart it worked for me.

**Comment by Mattiny** [comment]
@proti1 Thanks a lot for your feedback. This helps a lot to investigate this case further and to find a solution. Now i can try to reproduce this error and to hopefully fix it.

**Comment by Mattiny** [comment]
Fix in 1.2.0: Generating position takes place in "physics_process". So the raycast works even in multithreaded configuration.

**Comment by Mattiny** [comment]
Fix in 1.2.0: Generating position takes place in "physics_process". So the raycast works even in multithreaded configuration.
